In [7]:
import pandas as pd

df = pd.read_csv(r'zippedData\tmdb.movies.csv.gz',index_col=0)
df.sort_values('vote_average',ascending=False)

,genre_ids,id,original_language,original_title,popularity,release_date,title,vote_average,vote_count
13258,[99],403294,en,9/11: Simulations,0.600,2014-07-04,9/11: Simulations,10.0,1
22787,"[27, 35]",444170,en,Lasagna Cat - Telephone Sex Survey Results,0.722,2017-02-23,Lasagna Cat - Telephone Sex Survey Results,10.0,1
22592,[99],488357,en,MOTO 9: The Movie,0.900,2017-11-21,MOTO 9: The Movie,10.0,1
22607,[],437448,en,The Letter Carrier,0.895,2017-01-27,The Letter Carrier,10.0,1
22610,"[9648, 37, 18, 10402]",463601,en,Hope This Goes Over Well/Living in an Empty World,0.894,2017-06-26,Hope This Goes Over Well/Living in an Empty World,10.0,1
...,...,...,...,...,...,...,...,...,...
11018,[],124727,en,Darkchylde,0.600,2013-08-09,Darkchylde,0.0,1
14168,[],167531,en,Summer Snow,0.600,2014-07-25,Summer Snow,0.0,1
14167,"[99, 10402]",221918,en,Butch Walker: Out of Focus,0.600,2014-08-05,Butch Walker: Out of Focus,0.0,1
20601,"[18, 35]",448105,en,The Angry Man,0.600,2017-04-08,The Angry Man,0.0,1
26516,"[53, 27]",309885,en,The Church,0.600,2018-10-05,The Church,0.0,1